#################
# DNA
#################

import collections

def countNucFrequency(seq):
    tmpFreqDict = {"A": 0, "C": 0, "G": 0, "T": 0}
    for nuc in seq:
        tmpFreqDict[nuc] += 1
    return tmpFreqDict

sample = "ACCAGCTGGCTGTCTCTCCTTTTCATTAATTGACGAAGCAGAAGAAATGAAGCGGAATCATGGTGACACGACCACTAGTCTTCTCGACTTGTGATATAAATGATTCTACCGCGGCAGGGCTTGAAACTCGAGCTCGCTTGACGTTCATGATTACGTGAGCCAGGCAGGTCTTACCCTAGTAGACGGCTGTTGTGTTCCGCCGTGGAACGTAGATGAGTTTCTCGAAAACGACAGCTGATCTTTGGAGGCTCCAAGGATTTAACCTAGTGATGCGTACGTTAAACCACAGTAAAAGGAAACCTGGACCCCGCCTTGGGAAAGACGAACCCACAGACCCAGACCAGTGTGAGGACCGAGCGACTAACTTCTGCAAAGCTTCGTACCTCACGAAACCTGTTACCAAGACGCGACTAATCTCAGGATATTGCTACACCCACTCGGGGCCCCTGTTAAATCCGGGGCCTGATGCCTCGTCTTTGTCGCATCCGGTATCATGGCCTTGCCTCAGCCTCACAGCTAAACGAATACCGACCGTCCATGATGGCTGAGTAAGCTTGGCGGCGATGCAGCGGGTAACCTCTGGGCGTATGGTCCCCGCCGGTTATGTAGACATAGTCTCGGGTCCCGGTGCTACAGATCAGCAGCTTTTGGAACTAGGCGACAGAGTTGGTCCGCAGCAAAGAGTAGGAGAAGGGAGCGATAACAGGTGGAGGGCTTGGAGCTATGGTGCAAATAAATGACGCTGGATCAATACTTTCTCTCGTAATTACGTTATTCGGCAGCCCGCGCGAGAAGCTCCCTTTCTAATGGCGTCTAAGTGTACCTAACTCAGCGGCTTCTCCCCGAGCCTAAACGGCGTCCCACGGTAATTACAATCGT"
result = countNucFrequency(sample)
print(" ".join([str(value) for key, value in result.items()]))
