#################
# REVC
#################

DNA_reverseComplement = {'A': 'T', 'T': 'A', 'G': 'C', 'C': 'G'}

def reverse_complement(seq):
    return "".join([DNA_reverseComplement[nuc] for nuc in seq])[::-1]

sample = "GTACTATGTGAGAGGATTGGTAGAGGGACCTTAATAGTATGAAGGCCGGCGGAACACGGGACTAAACCAGCAGGCTGATGCGGGCCTTGGCTCAAGGTAGTGGAGGATGCGCGAGCCGGAATGTTGTGGCATGTTGAGCGCGCTATAAGCACTTCCGAGGAGTCTTTTACAATTCAGCGGACTTTAGCTTTGACACCTGGCTACCCAACGATAGATCTAACACCGCATACCTTCTACTGACTCTGCACCCAAAAGGCCCCTGTCGTCGTCTACGCACCGATTCAGTTTCGTCGTTGGGTCTTAAGTGTATTAATATTCTCTACGGTGCACTAACACTCCAAATCTCACTGTCTGGTTGGGACTATGCGTAAGCATCCTTGGAACCATATTGAATCGCATGGACGGCCGTTAAGCCTTTCGACATCACGATAATTTCGTACATGTTACCGTACGGGGTGTCGTAGAAACCGCTTGCAACACTCTTGCGGCGTCATAATTCGTGAACTGCTGGGAACAGATGAACACTGCCAACCAATTCAGGAGTAGCAGATGATATAAACAATGGGCGCCTCTGCGAATCTCGTTAAGGGTTGTGCAAGTTGCCTTAACCGTCGAAGGGGAGTGCCACTGGCGGTCAGAAAAATGGTGCTCATTCGCGGCATTGACGCGACCATGGATGATCACGGCCCCCGCGTCAACCTTAAACGACCCTCGAACCTCACTTCTCGGCACGCTTTATCATTTTTGAAGATTAACACATAAACCTCCAGAGGCTAAGGACAATCGGAAAATCTCGCGACGCCCTGCACTTGACGTTTTTAGTTGAGATCCATTCTTTGGTCCGCATCCAGATGGGCACAAGCCCCTTGATGTTTTAGGTCCAGGCGCCTGCCGGGCCATCTTCCCCGATGTCGTGATGT"
print(reverse_complement(sample))


